name: bilt_login
description: "A login screen using firebase and multiple providers."
version: 0.0.1
homepage: https://github.com/bilt-app/bilt-login

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  sign_in_button: ^4.0.1
  google_sign_in: ^7.1.0
  flutter_facebook_auth: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
publish_to: 'none'
